// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.17.3
// source: tokeniser/tiktoken.proto

package go_tokeniser

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListEncodingNamesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListEncodingNamesRequest) Reset() {
	*x = ListEncodingNamesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tokeniser_tiktoken_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListEncodingNamesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEncodingNamesRequest) ProtoMessage() {}

func (x *ListEncodingNamesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tokeniser_tiktoken_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEncodingNamesRequest.ProtoReflect.Descriptor instead.
func (*ListEncodingNamesRequest) Descriptor() ([]byte, []int) {
	return file_tokeniser_tiktoken_proto_rawDescGZIP(), []int{0}
}

type ListEncodingNamesReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EncodingNames []string `protobuf:"bytes,1,rep,name=encoding_names,json=encodingNames,proto3" json:"encoding_names,omitempty"`
}

func (x *ListEncodingNamesReply) Reset() {
	*x = ListEncodingNamesReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tokeniser_tiktoken_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListEncodingNamesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEncodingNamesReply) ProtoMessage() {}

func (x *ListEncodingNamesReply) ProtoReflect() protoreflect.Message {
	mi := &file_tokeniser_tiktoken_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEncodingNamesReply.ProtoReflect.Descriptor instead.
func (*ListEncodingNamesReply) Descriptor() ([]byte, []int) {
	return file_tokeniser_tiktoken_proto_rawDescGZIP(), []int{1}
}

func (x *ListEncodingNamesReply) GetEncodingNames() []string {
	if x != nil {
		return x.EncodingNames
	}
	return nil
}

type GetTokenNumByEncodingNameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EncodingName string   `protobuf:"bytes,1,opt,name=encoding_name,json=encodingName,proto3" json:"encoding_name,omitempty"`
	Text         []string `protobuf:"bytes,2,rep,name=text,proto3" json:"text,omitempty"`
}

func (x *GetTokenNumByEncodingNameRequest) Reset() {
	*x = GetTokenNumByEncodingNameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tokeniser_tiktoken_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTokenNumByEncodingNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenNumByEncodingNameRequest) ProtoMessage() {}

func (x *GetTokenNumByEncodingNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tokeniser_tiktoken_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenNumByEncodingNameRequest.ProtoReflect.Descriptor instead.
func (*GetTokenNumByEncodingNameRequest) Descriptor() ([]byte, []int) {
	return file_tokeniser_tiktoken_proto_rawDescGZIP(), []int{2}
}

func (x *GetTokenNumByEncodingNameRequest) GetEncodingName() string {
	if x != nil {
		return x.EncodingName
	}
	return ""
}

func (x *GetTokenNumByEncodingNameRequest) GetText() []string {
	if x != nil {
		return x.Text
	}
	return nil
}

type GetTokenNumReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NTokens []int64 `protobuf:"varint,1,rep,packed,name=n_tokens,json=nTokens,proto3" json:"n_tokens,omitempty"`
}

func (x *GetTokenNumReply) Reset() {
	*x = GetTokenNumReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tokeniser_tiktoken_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTokenNumReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenNumReply) ProtoMessage() {}

func (x *GetTokenNumReply) ProtoReflect() protoreflect.Message {
	mi := &file_tokeniser_tiktoken_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenNumReply.ProtoReflect.Descriptor instead.
func (*GetTokenNumReply) Descriptor() ([]byte, []int) {
	return file_tokeniser_tiktoken_proto_rawDescGZIP(), []int{3}
}

func (x *GetTokenNumReply) GetNTokens() []int64 {
	if x != nil {
		return x.NTokens
	}
	return nil
}

type GetTokenNumByModelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Model string   `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Text  []string `protobuf:"bytes,2,rep,name=text,proto3" json:"text,omitempty"`
}

func (x *GetTokenNumByModelRequest) Reset() {
	*x = GetTokenNumByModelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tokeniser_tiktoken_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTokenNumByModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenNumByModelRequest) ProtoMessage() {}

func (x *GetTokenNumByModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tokeniser_tiktoken_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenNumByModelRequest.ProtoReflect.Descriptor instead.
func (*GetTokenNumByModelRequest) Descriptor() ([]byte, []int) {
	return file_tokeniser_tiktoken_proto_rawDescGZIP(), []int{4}
}

func (x *GetTokenNumByModelRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *GetTokenNumByModelRequest) GetText() []string {
	if x != nil {
		return x.Text
	}
	return nil
}

var File_tokeniser_tiktoken_proto protoreflect.FileDescriptor

var file_tokeniser_tiktoken_proto_rawDesc = []byte{
	0x0a, 0x18, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x69, 0x73, 0x65, 0x72, 0x2f, 0x74, 0x69, 0x6b, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x69, 0x73, 0x65, 0x72, 0x22, 0x1a, 0x0a, 0x18, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x6e, 0x63,
	0x6f, 0x64, 0x69, 0x6e, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x3f, 0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e,
	0x67, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x25, 0x0a, 0x0e, 0x65,
	0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x0d, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x4e, 0x61, 0x6d,
	0x65, 0x73, 0x22, 0x5b, 0x0a, 0x20, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x4e, 0x75,
	0x6d, 0x42, 0x79, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x69,
	0x6e, 0x67, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65,
	0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22,
	0x2d, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x4e, 0x75, 0x6d, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x19, 0x0a, 0x08, 0x6e, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x07, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x22, 0x45,
	0x0a, 0x19, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x4e, 0x75, 0x6d, 0x42, 0x79, 0x4d,
	0x6f, 0x64, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x04, 0x74, 0x65, 0x78, 0x74, 0x32, 0xb1, 0x02, 0x0a, 0x0c, 0x54, 0x69, 0x6b, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x69, 0x73, 0x65, 0x72, 0x12, 0x5d, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x6e,
	0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x23, 0x2e, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x69, 0x73, 0x65, 0x72, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x6e, 0x63, 0x6f,
	0x64, 0x69, 0x6e, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x21, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x69, 0x73, 0x65, 0x72, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x67, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x4e, 0x75, 0x6d, 0x42, 0x79, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x2b, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x69, 0x73, 0x65, 0x72, 0x2e, 0x47,
	0x65, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x4e, 0x75, 0x6d, 0x42, 0x79, 0x45, 0x6e, 0x63, 0x6f,
	0x64, 0x69, 0x6e, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1b, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x69, 0x73, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x59,
	0x0a, 0x12, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x4e, 0x75, 0x6d, 0x42, 0x79, 0x4d,
	0x6f, 0x64, 0x65, 0x6c, 0x12, 0x24, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x69, 0x73, 0x65, 0x72,
	0x2e, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x4e, 0x75, 0x6d, 0x42, 0x79, 0x4d, 0x6f,
	0x64, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x69, 0x73, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x4e,
	0x75, 0x6d, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x1b, 0x5a, 0x19, 0x74, 0x69, 0x6b,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2f, 0x73, 0x64, 0x6b, 0x2f, 0x67, 0x6f, 0x2d, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x69, 0x73, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tokeniser_tiktoken_proto_rawDescOnce sync.Once
	file_tokeniser_tiktoken_proto_rawDescData = file_tokeniser_tiktoken_proto_rawDesc
)

func file_tokeniser_tiktoken_proto_rawDescGZIP() []byte {
	file_tokeniser_tiktoken_proto_rawDescOnce.Do(func() {
		file_tokeniser_tiktoken_proto_rawDescData = protoimpl.X.CompressGZIP(file_tokeniser_tiktoken_proto_rawDescData)
	})
	return file_tokeniser_tiktoken_proto_rawDescData
}

var file_tokeniser_tiktoken_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_tokeniser_tiktoken_proto_goTypes = []interface{}{
	(*ListEncodingNamesRequest)(nil),         // 0: tokeniser.ListEncodingNamesRequest
	(*ListEncodingNamesReply)(nil),           // 1: tokeniser.ListEncodingNamesReply
	(*GetTokenNumByEncodingNameRequest)(nil), // 2: tokeniser.GetTokenNumByEncodingNameRequest
	(*GetTokenNumReply)(nil),                 // 3: tokeniser.GetTokenNumReply
	(*GetTokenNumByModelRequest)(nil),        // 4: tokeniser.GetTokenNumByModelRequest
}
var file_tokeniser_tiktoken_proto_depIdxs = []int32{
	0, // 0: tokeniser.Tiktokeniser.ListEncodingNames:input_type -> tokeniser.ListEncodingNamesRequest
	2, // 1: tokeniser.Tiktokeniser.GetTokenNumByEncodingName:input_type -> tokeniser.GetTokenNumByEncodingNameRequest
	4, // 2: tokeniser.Tiktokeniser.GetTokenNumByModel:input_type -> tokeniser.GetTokenNumByModelRequest
	1, // 3: tokeniser.Tiktokeniser.ListEncodingNames:output_type -> tokeniser.ListEncodingNamesReply
	3, // 4: tokeniser.Tiktokeniser.GetTokenNumByEncodingName:output_type -> tokeniser.GetTokenNumReply
	3, // 5: tokeniser.Tiktokeniser.GetTokenNumByModel:output_type -> tokeniser.GetTokenNumReply
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tokeniser_tiktoken_proto_init() }
func file_tokeniser_tiktoken_proto_init() {
	if File_tokeniser_tiktoken_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tokeniser_tiktoken_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListEncodingNamesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tokeniser_tiktoken_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListEncodingNamesReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tokeniser_tiktoken_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTokenNumByEncodingNameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tokeniser_tiktoken_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTokenNumReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tokeniser_tiktoken_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTokenNumByModelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tokeniser_tiktoken_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tokeniser_tiktoken_proto_goTypes,
		DependencyIndexes: file_tokeniser_tiktoken_proto_depIdxs,
		MessageInfos:      file_tokeniser_tiktoken_proto_msgTypes,
	}.Build()
	File_tokeniser_tiktoken_proto = out.File
	file_tokeniser_tiktoken_proto_rawDesc = nil
	file_tokeniser_tiktoken_proto_goTypes = nil
	file_tokeniser_tiktoken_proto_depIdxs = nil
}
